services:
  postgres:
    image: postgres:16-alpine
    container_name: booksbox-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: booksbox
      POSTGRES_PASSWORD: booksbox
      POSTGRES_DB: booksbox
    ports:
      - "5432:5432"
    volumes:
      - booksbox-postgres:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit
    container_name: booksbox-mailpit
    restart: unless-stopped
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  booksbox-postgres:
